apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-articles
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-articles
  template:
    metadata:
      labels:
        app: go-articles
    spec:
      containers:
      - name: go-articles-rest
        image: cr.yandex/crphaucid3cc0uao4tq8/go-articles:2021.11.2-1
